"""Criar tabelas iniciais

Revision ID: 155d8a86a26d
Revises: 
Create Date: 2025-01-15 18:36:34.231682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155d8a86a26d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_categorias_id', table_name='categorias')
    op.alter_column('jogos', 'desenvolvedor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jogos', 'estoque',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jogos', 'data_lancamento',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_jogos_id', table_name='jogos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jogos_id', 'jogos', ['id'], unique=False)
    op.alter_column('jogos', 'data_lancamento',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('jogos', 'estoque',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jogos', 'desenvolvedor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_categorias_id', 'categorias', ['id'], unique=False)
    op.alter_column('categorias', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
