"""Adicionar campo classificacao_etaria em jogos

Revision ID: 62a8c1f86c14
Revises: 155d8a86a26d
Create Date: 2025-01-15 18:38:30.411240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a8c1f86c14'
down_revision: Union[str, None] = '155d8a86a26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogos', sa.Column('classificacao_etaria', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jogos', 'classificacao_etaria')
    # ### end Alembic commands ###
