"""Adiciona entidade Plataforma

Revision ID: 67747723543f
Revises: f8c6ad5e08a4
Create Date: 2025-01-16 19:39:52.766928

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67747723543f'
down_revision: Union[str, None] = 'f8c6ad5e08a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar a tabela de plataformas
    op.create_table('plataformas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('fabricante', sa.String(), nullable=False),
        sa.Column('suporte_online', sa.Boolean(), nullable=True),
        sa.Column('tipo', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Criar a tabela de associação entre jogos e plataformas
    op.create_table('jogo_plataforma',
        sa.Column('jogo_id', sa.Integer(), nullable=False),
        sa.Column('plataforma_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id']),
        sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id']),
        sa.PrimaryKeyConstraint('jogo_id', 'plataforma_id')
    )
    
    # Preencher os valores nulos na coluna data_criacao com um valor padrão (exemplo: 2025-01-01)
    op.execute(
        "UPDATE categorias SET data_criacao = '2025-01-01' WHERE data_criacao IS NULL"
    )

    # Alterar a coluna data_criacao para NOT NULL
    op.alter_column('categorias', 'data_criacao',
               existing_type=sa.DATE(),
               nullable=False)
    
    # Alterar a coluna ativo para permitir valores nulos
    op.alter_column('categorias', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorias', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    
    op.alter_column('categorias', 'data_criacao',
               existing_type=sa.DATE(),
               nullable=True)
    
    # Remover as tabelas criadas
    op.drop_table('jogo_plataforma')
    op.drop_table('plataformas')
    # ### end Alembic commands ###
