"""Remover campo classificacao_etaria em jogos

Revision ID: a05b0cdad49f
Revises: 62a8c1f86c14
Create Date: 2025-01-15 18:40:57.705454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05b0cdad49f'
down_revision: Union[str, None] = '62a8c1f86c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jogos', 'classificacao_etaria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogos', sa.Column('classificacao_etaria', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
